### ISSUE TITLE
Error: 'str' object has no attribute 'capabilities

### ISSUE THREAD

**Issue by tbrodbeck** [antonengelhardt/kicktipp-bot#28]
## Environment

- Docker: Desktop 4.30.0 (149282)
- OS: macOS 14.5 

## Pre-Condition

```
➜  kicktipp-bot git:(main) docker pull ghcr.io/antonengelhardt/kicktipp-bot:amd64
amd64: Pulling from antonengelhardt/kicktipp-bot
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Even though I am using a M1 Max Macbook, Docker is able running the amd64 image through emulation. (see below)

## Expected Behavior

I just tried booting up the container.

## Actual Behavior

```
kicktipp-bot git:(main) docker run -it --name kicktipp-bot --platform linux/amd64 --env-file .env ghcr.io/antonengelhardt/kicktipp-bot:amd64
Unable to find image 'ghcr.io/antonengelhardt/kicktipp-bot:amd64' locally
amd64: Pulling from antonengelhardt/kicktipp-bot
d25f557d7f31: Pulling fs layer 
420fafe905e6: Pull complete 
655dbd150ead: Pull complete 
cdbfaba2cf0b: Pull complete 
218bfc3b710f: Pull complete 
e1ec0bee04fe: Pull complete 
7eb9c839b2a8: Downloading [==>                                                ]  13.36MB/252.6MB
7eb9c839b2a8: Pull complete 
4864fe4d5b8b: Pull complete 
d789597b21d6: Pull complete 
a06ad60dc2be: Pull complete 
a6256c8db3cd: Pull complete 
2c77f028a598: Pull complete 
c5e890516ee9: Pull complete 
7ddd4957a89f: Pull complete Digest: sha256:31358a354c72759d83f964446352fedf4700e4859cdd69b6eb01353340a0e5ea
Status: Downloaded newer image for ghcr.io/antonengelhardt/kicktipp-bot:amd64
18.06.24 11:04: The script will execute now!

Custom Chrome Driver Path

'str' object has no attribute 'capabilities'

18.06.24 11:04: The script has finished. Sleeping for 1 hour...
```

## Additional Information

I tried building the docker container myself (running ARM), but I got the same error. So it does not seem not architecture related.

**Comment by tbrodbeck** [comment]
Ok I found the error. The chromedriver path was not valid of the .env.example. I needed to delete it then it it works

**Comment by antonengelhardt** [comment]
yeah, sorry... ill remove this in my next PR when i work on ARM support

**Comment by tbrodbeck** [comment]
No worries. Nice bot otherwise :)

**Comment by tbrodbeck** [comment]
I exchanged the business logic a little bit with my own system. I can send you a PR if you are interested after I get it cleaned up

**Comment by antonengelhardt** [comment]
> I exchanged the business logic a little bit with my own system. I can send you a PR if you are interested after I get it cleaned up

Yes, sure 👍🏻

**Comment by tbrodbeck** [comment]
Hey. I have chosen a quite different approach now.

I have put it in its own repo for now: https://github.com/tbrodbeck/kicktipp-bot-serverless

The main difference between my approach and yours is that this tool is...
1. it is intended to be run as a job not as a service. So it will stop immediately after checking the games and requires an external scheduling tool such as Cron, GCP Cloud Run Code Triggers or AWS EventBridge.
2. using PlayWright instead of Selenium. (which is a bit nicer/more modern to use)

Especially, because I used PlayWright - I am not sure how to merge those two repositories anymore.

**Comment by antonengelhardt** [comment]
> Hey. I have chosen a quite different approach now.
> 
> I have put it in its own repo for now: https://github.com/tbrodbeck/kicktipp-bot-serverless
> 
> The main difference between my approach and yours is that this tool is...
> 
> 1. it is intended to be run as a job not as a service. So it will stop immediately after checking the games and requires an external scheduling tool such as Cron, GCP Cloud Run Code Triggers or AWS EventBridge.

I like that idea. We could introduce an environment variable or argument flag (`--schedule X`) which tells the bot to run itself every `X` minutes. If not set, the bot will run once and can be scheduled by a CronJob or some other scheduler. 

> 2. using PlayWright instead of Selenium. (which is a bit nicer/more modern to use)

I do not have much experience with playwright and Selenium works well enough for me. The only annoying this is that i am unable to build an ARM Image with Selenium, because the Chromedriver does not seem to work. Does Playwright work with ARM?

> Especially, because I used PlayWright - I am not sure how to merge those two repositories anymore.

Thats totally ok. I can reference your repo in the readme, so people can choose.

**Comment by tbrodbeck** [comment]
Hi Anton. Sounds good. Would be lovely to be mentioned in the README of this repo :) 

And yeah what can I say.. The bot is working fine so far in our little group:  😄 
<img width="431" alt="Screenshot 2024-07-08 at 19 08 54" src="https://github.com/antonengelhardt/kicktipp-bot/assets/24418160/07b4aaaa-9a05-4d26-8211-d4cd774642c5">

**Comment by antonengelhardt** [comment]
Hey Tillus,

Awesome man! In the World Cup, i got seconds two years ago.

I will create a PR now.
