### ISSUE TITLE
 Notifications to generic webhook (e.g. Homeassistant) 

### ISSUE THREAD

**Issue by DenisMir** [antonengelhardt/kicktipp-bot#36]
It would be nice if you could add notifications to a generic POST webhook. For example homeassistant allows to generate webhook URLs that you can POST generic data to. (e.g. JSON data) The notification itself is done inside HA with a custom automation that you do not have to take care off. Just post the notification data to the webhook URL.

**Comment by antonengelhardt** [comment]
Hey @DenisMir,

thanks for the idea!

I have opened a [PR](https://github.com/antonengelhardt/kicktipp-bot/pull/37). Can you test and let me know if this works for you? I dont have HA, so i cannot test.

**Comment by DenisMir** [comment]
Hey @antonengelhardt. Yeah for sure I will test it and get back to you here.

**Comment by DenisMir** [comment]
Das ganze funktioniert auf jeden Fall. 

<img width="530" alt="Bildschirmfoto 2024-08-25 um 10 10 12" src="https://github.com/user-attachments/assets/ddca10ed-f176-4077-ae41-cfa0a2145aa7">

**Comment by antonengelhardt** [comment]
PR is updated @DenisMir
